defaults:
    - agent: sac

env: cheetah_run

pytorch_sac_ae: true
frame_stack: 3
# this needs to be specified manually
experiment: test_exp

num_train_steps: 1e6
replay_buffer_capacity: ${num_train_steps}

num_seed_steps: 5000

eval_frequency: 10
num_eval_episodes: 10
num_curriculum_eval_episodes: 10

reset_initial_pos_only: True
device: cuda

# logger
log_frequency: 10000
log_save_tb: true

# video recorder
save_video: true
save_model: true
save_buffer: true

seed: 1

encoder_type: pixel
frame_stack: 3

# hydra configuration
hydra:
    name: ${env}
    run:
        dir: ./exp/${now:%Y.%m.%d}/${now:%H%M}_${agent.name}_${experiment}

pretrained: False
curriculum: True
record_params: ['rgb', 'depth', 'map']

#gibson_cfg: /private/home/jtruong/repos/pytorch_sac/config/locobot_p2p_nav_house_sac.yaml
gibson_cfg: /private/home/jtruong/repos/pytorch_sac/config/locobot_p2p_nav_house_sac_ae.yaml
#gibson_cfg: /private/home/jtruong/repos/pytorch_sac_4/pytorch_sac/config/locobot_p2p_nav_house_sac_ae_stadium.yaml
#gibson_cfg: /private/home/jtruong/repos/pytorch_sac/config/locobot_p2p_nav_house_sac_stadium.yaml
