defaults:
    - agent: sac

env: cheetah_run

# this needs to be specified manually
experiment: test_exp

num_train_steps: 1e6
replay_buffer_capacity: ${num_train_steps}

num_seed_steps: 5000

eval_frequency: 10
num_eval_episodes: 10

device: cuda

# logger
log_frequency: 10000
log_save_tb: true

# video recorder
save_video: true
save_model: true
save_buffer: true

seed: 1


# hydra configuration
hydra:
    name: ${env}
    run:
        dir: ./exp/${now:%Y.%m.%d}/${now:%H%M}_${agent.name}_${experiment}

#gibson_cfg: /private/home/jtruong/repos/pytorch_sac/config/locobot_p2p_nav_house_sac.yaml
gibson_cfg: /private/home/jtruong/repos/dynamics_aware_navigation/pytorch_sac/config/daisy_demo.yaml
